// SALES OS 2.0 — PHASE 1: TODAY / SALES DIRECTOR
SalesOS.conversationCount=function(){return (DB.salesActivities||[]).filter(a=>SalesOS.activityToday(a)&&/spoke|conversation|decision maker|interested|meeting booked|proposal/i.test(String(a.outcome||''))).length;};
SalesOS.decisionMakerTouches=function(){return (DB.salesActivities||[]).filter(a=>SalesOS.activityToday(a)&&/decision maker/i.test(String(a.outcome||''))).length;};
SalesOS.qualifiedPipeline=function(){
 const opps=(DB.opportunities||[]).filter(o=>!['Won','Lost'].includes(o.stage));
 return opps.reduce((s,o)=>s+Number(o.value||0),0);
};
SalesOS.weightedPipeline=function(){
 const opps=(DB.opportunities||[]).filter(o=>!['Won','Lost'].includes(o.stage));
 return opps.reduce((s,o)=>s+Number(o.value||0)*Number(o.probability||0)/100,0);
};
SalesOS.revenueAtRisk=function(){
 return (DB.opportunities||[]).filter(o=>!['Won','Lost'].includes(o.stage)&&(!o.nextAction||!o.nextFollowup||o.nextFollowup<currentDateStr())).reduce((s,o)=>s+Number(o.value||0),0);
};
SalesOS.work30=function(){const q=SalesOS.queue().filter(l=>l.phone||l.email).slice(0,6);if(!q.length){toast('No contactable prospects are available','error');return;}SalesOS.sessionOpen=true;SalesOS.sessionQueue=q.map(x=>x.id);SalesOS.activeLeadId=q[0].id;renderSection();setTimeout(()=>document.getElementById('sales-os-session')?.scrollIntoView({behavior:'smooth'}),50);};
SalesOS.nextObjective=function(lead){if(!lead.contactName)return 'Identify the organiser or decision maker';if(lead.status==='Proposal Sent')return 'Agree a decision date and surface any blocker';if(lead.status==='Proposal Required')return 'Confirm requirements and send the tailored proposal';if(lead.status==='Meeting Booked')return 'Prepare discovery and confirm the meeting';if(lead.relationship==='Hot'||lead.relationship==='Warm')return 'Secure a meeting or venue visit';return 'Create a two-way conversation and agree a dated next step';};
SalesOS.renderMission=function(){
 const stats=SalesOS.todayStats(),health=SalesOS.pipelineHealth(),queue=SalesOS.queue().slice(0,8),qualified=SalesOS.qualifiedPipeline(),weighted=SalesOS.weightedPipeline(),risk=SalesOS.revenueAtRisk(),convos=SalesOS.conversationCount(),dm=SalesOS.decisionMakerTouches();
 const sessionQueue=(SalesOS.sessionQueue||queue.map(x=>x.id)).map(id=>(DB.salesLeads||[]).find(x=>x.id===id)).filter(Boolean).slice(0,6);
 const scoreboard=[['Calls',stats.calls,20,false],['Conversations',convos,8,false],['Decision Makers',dm,3,false],['Meetings',stats.meetings,2,false],['Pipeline Created',stats.pipeline,5000,true]].map(([l,v,t,m])=>`<div><div class="flex justify-between text-xs"><span>${l}</span><strong>${m?SalesOS.money(v):v}/${m?SalesOS.money(t):t}</strong></div><div class="h-2 bg-gray-100 rounded-full mt-2 overflow-hidden"><div class="h-full bg-olive-600" style="width:${SalesOS.progress(v,t)}%"></div></div></div>`).join('');
 const queueHtml=queue.length?queue.map((lead,i)=>`<article class="p-4 flex gap-4 items-start"><span class="w-9 h-9 rounded-full ${i<3?'bg-gold-500 text-white':'bg-olive-100 text-olive-700'} flex items-center justify-center font-bold flex-shrink-0">${i+1}</span><div class="flex-1"><div class="flex gap-2 flex-wrap items-center"><strong>${esc(lead.companyName)}</strong><span class="badge ${salesLeadStatusColor(lead.status)}">${esc(lead.status)}</span>${salesLeadOverdue(lead)?'<span class="badge bg-red-100 text-red-700">Overdue</span>':''}</div><p class="text-xs text-gray-500 mt-1">${esc(lead.contactName||'Decision maker missing')} · ${SalesOS.money(lead.potentialValue)}</p><div class="mt-3 grid md:grid-cols-2 gap-2"><div class="rounded-lg bg-red-50 p-3"><span class="text-[9px] font-bold text-red-700">WHY NOW</span><p class="text-xs mt-1">${esc(SalesOS.priorityReason(lead))}</p></div><div class="rounded-lg bg-olive-50 p-3"><span class="text-[9px] font-bold text-olive-700">OBJECTIVE</span><p class="text-xs mt-1">${esc(SalesOS.nextObjective(lead))}</p></div></div></div><button onclick="SalesOS.openLiveCall('${lead.id}')" class="px-3 py-2 bg-charcoal-900 text-white rounded-lg text-xs font-bold">Work Now</button></article>`).join(''):`<div class="p-8 text-center text-gray-400">Add target businesses to create today's plan.</div>`;
 const sessionHtml=SalesOS.sessionOpen?`<div class="divide-y">${sessionQueue.map((lead,i)=>`<div class="p-4 flex items-center gap-4"><span class="text-sm font-bold text-gray-400">${i+1}</span><div class="flex-1"><strong>${esc(lead.companyName)}</strong><p class="text-xs text-gray-500">${esc(SalesOS.nextObjective(lead))}</p></div><button onclick="SalesOS.openLiveCall('${lead.id}')" class="px-3 py-2 rounded-lg ${i===0?'bg-olive-700 text-white':'bg-gray-100'} text-xs font-bold">${i===0?'Start':'Open'}</button></div>`).join('')}</div>`:`<div class="p-8 text-center"><p class="text-sm text-gray-500">Start a normal session or use 30-minute mode for the six best contactable prospects.</p><div class="flex justify-center gap-2 mt-4"><button onclick="SalesOS.openSalesSession()" class="px-4 py-2 bg-charcoal-900 text-white rounded-lg font-bold">Start Session</button><button onclick="SalesOS.work30()" class="px-4 py-2 bg-gold-500 text-white rounded-lg font-bold">30-Minute Sprint</button></div></div>`;
 return `<div class="rounded-3xl bg-gradient-to-r from-charcoal-900 via-[#34402b] to-olive-800 text-white p-5 lg:p-7 shadow-lg mb-5"><div class="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-5"><div><p class="text-xs font-bold tracking-[.2em] text-gold-300">WINDMILL SALES OS · TODAY</p><h2 class="text-2xl lg:text-4xl font-bold mt-1">What revenue can we create today?</h2><p class="text-sm text-white/70 mt-3 max-w-3xl">Work the best opportunities first. Every conversation should create a decision maker, meeting, qualified opportunity, proposal, decision date or a dated next step.</p></div><div class="flex gap-2 flex-wrap"><button onclick="SalesOS.work30()" class="px-4 py-3 bg-gold-500 text-white rounded-xl font-bold">I've Got 30 Minutes</button><button onclick="SalesOS.openSalesSession()" class="px-4 py-3 bg-white text-charcoal-900 rounded-xl font-bold">Start Sales Session</button><button onclick="SalesOS.intelligenceMode='finder';SalesOS.setView('intelligence')" class="px-4 py-3 bg-blue-100 text-blue-950 rounded-xl font-bold">Find Business</button><button onclick="openSalesLeadForm()" class="px-4 py-3 bg-white/10 border border-white/20 rounded-xl font-semibold">+ Target Business</button></div></div></div>
 ${window.SalesOS?.renderAuditBanner?SalesOS.renderAuditBanner():''}
 <div class="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-4">${SalesOS.kpi('Qualified Pipeline',SalesOS.money(qualified),'Formal open Opportunities only','badge-pound-sterling','olive')}${SalesOS.kpi('Weighted Forecast',SalesOS.money(weighted),'Evidence-weighted formal Opportunities','chart-no-axes-combined','blue')}${SalesOS.kpi('Revenue Needing Action',SalesOS.money(risk),'Overdue or uncontrolled formal Opportunity value','triangle-alert',risk?'red':'green')}${SalesOS.kpi('Priority Prospects',queue.length,'Ranked by urgency, value and relationship','crosshair','gold')}</div>
 <section class="bg-white rounded-2xl border border-gray-200 shadow-sm p-4 mb-5"><div class="flex flex-col lg:flex-row lg:items-center gap-4"><div class="lg:w-44"><p class="text-xs font-bold tracking-widest text-olive-700">TODAY'S SCOREBOARD</p><p class="text-[11px] text-gray-500 mt-1">Inputs → outcomes → revenue</p></div><div class="grid grid-cols-2 md:grid-cols-5 gap-3 flex-1">${scoreboard}</div></div></section>
 <div class="grid xl:grid-cols-[1.35fr_.65fr] gap-4 mb-5">${SalesOS.panel('Do Now','Your Sales Director has ranked these by urgency, commercial value and likelihood of movement',`<div class="divide-y divide-gray-100 -mx-5 -my-5">${queueHtml}</div>`)}<div class="space-y-4"><section class="rounded-2xl bg-charcoal-900 text-white p-5"><p class="text-xs text-olive-200">PIPELINE CONTROL</p><p class="text-4xl font-bold mt-1">${health.score}/100</p><p class="text-sm text-white/60">${health.label}</p><div class="grid grid-cols-2 gap-2 mt-4 text-xs"><div class="bg-white/10 rounded-lg p-3">Controlled<strong class="block text-lg">${health.controlled.length}/${health.leads.length}</strong></div><div class="bg-white/10 rounded-lg p-3">Overdue<strong class="block text-lg">${health.overdue.length}</strong></div><div class="bg-white/10 rounded-lg p-3">Decision makers<strong class="block text-lg">${health.decisionMakers.length}</strong></div><div class="bg-white/10 rounded-lg p-3">With value<strong class="block text-lg">${health.valued.length}</strong></div></div></section>${SalesOS.panel('Sales rule','What good looks like','<p class="text-sm"><strong>Never finish with “spoke to customer”.</strong></p><p class="text-xs text-gray-500 mt-2">Finish with a meeting, proposal, decision date, qualification milestone, valid lost reason or dated next action.</p>')}</div></div>
 ${window.SalesOS?.renderRevivePanel?SalesOS.renderRevivePanel():''}
 <section id="sales-os-session" class="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden"><div class="px-5 py-4 border-b"><p class="text-xs font-bold tracking-widest text-olive-700">FOCUSED SALES SESSION</p><h3 class="font-bold text-xl">${SalesOS.sessionOpen?'Work the queue — one prospect at a time':'Ready when you are'}</h3><p class="text-xs text-gray-500 mt-1">The system chooses the order; the manager creates the relationship.</p></div>${sessionHtml}</section>`;
};
