import { AlertTriangle, CheckCircle2, Database, FileStack, LockKeyhole, ShieldCheck } from "lucide-react";
import type { WeddingOperationalModel } from "@/features/weddings/types/operational-model";
import { weddingOutputRegistry } from "@/features/weddings/lib/output-registry";
export function OutputFoundation({model}:{model:WeddingOperationalModel}){return <div className="space-y-6">
<section className="overflow-hidden rounded-[32px] bg-backstage-ink p-7 text-white lg:p-9"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-backstage-gold"><Database size={16}/> Wedding Operational Model</div><h2 className="backstage-display mt-4 max-w-4xl text-4xl lg:text-5xl">One wedding truth. Every document consumes it.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-white/55">This layer normalises the wedding before any PDF is produced, so Function Sheets, Kitchen Prep, customer summaries and supplier handovers cannot quietly invent different guest numbers or timings.</p><div className="mt-7 grid gap-3 sm:grid-cols-4"><Metric label="Readiness" value={`${model.readiness.score}%`}/><Metric label="Day guests" value={String(model.guestSummary.day)}/><Metric label="Dietary guests" value={String(model.guestSummary.dietaryGuests)}/><Metric label="Blockers" value={String(model.readiness.blockers)}/></div></section>
<section className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="backstage-panel rounded-3xl p-6 lg:p-7"><div className="backstage-kicker">Normalised facts</div><h3 className="backstage-display mt-2 text-3xl">What outputs are allowed to trust</h3><div className="mt-5 space-y-3">{model.facts.map(f=><div key={f.key} className="flex items-center justify-between gap-4 rounded-2xl border border-black/10 bg-white p-4"><div><div className="font-semibold">{f.label}</div><div className="mt-1 text-xs text-black/35">{f.source}</div></div><div className="text-right"><div className="font-semibold">{String(f.value??"Missing")}</div><div className={`mt-1 text-[11px] font-bold uppercase tracking-[.1em] ${f.confidence==="confirmed"?"text-[#66806B]":f.confidence==="missing"?"text-[#B75E51]":"text-[#9A793F]"}`}>{f.confidence}</div></div></div>)}</div></div>
<div className="space-y-6"><div className="backstage-panel rounded-3xl p-6"><div className="backstage-kicker">Issue gate</div><h3 className="backstage-display mt-2 text-3xl">{model.readiness.canIssueOperationalPack?"Foundation is issue-safe":"Operational pack is blocked"}</h3><div className="mt-4 space-y-3">{model.issues.length?model.issues.map(i=><div key={i.id} className="flex gap-3 rounded-2xl bg-black/[.025] p-3">{i.level==="blocker"?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}<div><div className="text-sm font-semibold">{i.area}</div><div className="mt-1 text-xs leading-5 text-black/45">{i.message}</div></div></div>):<div className="text-sm text-black/50">No foundation issues detected.</div>}</div></div><div className="backstage-panel rounded-3xl p-6"><div className="flex gap-3"><ShieldCheck size={18}/><div><div className="font-semibold">Change fingerprints are built in</div><p className="mt-1 text-sm leading-6 text-black/45">Planning, guests, timings and commercial data each have a fingerprint. Issued documents can later become stale automatically after a meaningful change.</p></div></div></div></div></section>
<section className="backstage-panel rounded-3xl p-6 lg:p-7"><div className="flex items-center gap-2"><FileStack size={18}/><div><div className="backstage-kicker">Output contract</div><h3 className="backstage-display mt-1 text-3xl">Documents this model will power</h3></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{weddingOutputRegistry.map(o=><div key={o.key} className="rounded-3xl border border-black/10 bg-white p-5"><div className="flex justify-between gap-3"><div className="font-semibold">{o.name}</div><span className="rounded-full bg-black/[.04] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-black/40">{o.status}</span></div><p className="mt-2 text-sm leading-6 text-black/45">{o.purpose}</p><div className="mt-4 flex flex-wrap gap-1.5">{o.requiredDomains.map(x=><span key={x} className="rounded-full border border-black/10 px-2 py-1 text-[10px] text-black/40">{x}</span>)}</div></div>)}</div><div className="mt-5 flex items-center gap-2 rounded-2xl bg-[#F3EADB] p-4 text-sm text-[#755E36]"><LockKeyhole size={16}/> PDF styling comes after the data contract. No document gets its own private guest-count or dietary logic.</div></section>
</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-3xl border border-white/10 bg-white/[.05] p-4"><div className="text-xs text-white/35">{label}</div><div className="backstage-display mt-1 text-3xl">{value}</div></div>}