"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, Clock3, HeartHandshake, LockKeyhole, PoundSterling, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import type { WeddingRecord } from "../types/wedding";

const money = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 });
function dateValue(value: string) { return new Date(`${value}T12:00:00`).getTime(); }
function formatDate(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", year: "numeric" }); }

export function WeddingsCommandCentre({ weddings, demoMode }: { weddings: WeddingRecord[]; demoMode: boolean }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("active");
  const visible = useMemo(() => weddings.filter((wedding) => {
    if (status !== "active" && wedding.status !== status) return false;
    if (status === "active" && wedding.status === "completed") return false;
    const needle = query.trim().toLowerCase();
    return !needle || [wedding.couple, wedding.packageName, wedding.coordinator, wedding.status].some((value) => value.toLowerCase().includes(needle));
  }).sort((a, b) => dateValue(a.eventDate) - dateValue(b.eventDate)), [query, status, weddings]);
  const active = weddings.filter((wedding) => wedding.status !== "completed");
  const outstanding = active.reduce((sum, wedding) => sum + Math.max(0, wedding.quotedValue - wedding.paidValue), 0);
  const needsAttention = active.filter((wedding) => wedding.readinessScore < 75);
  const ready = active.filter((wedding) => wedding.readinessScore >= 90);

  return <div className="mx-auto max-w-[1650px] space-y-6">
    <section className="backstage-wedding-photo relative min-h-[390px] overflow-hidden rounded-[32px] text-white"><div className="absolute inset-0 bg-gradient-to-r from-[#0B141E]/92 via-[#0B141E]/62 to-[#0B141E]/15"/><div className="relative flex min-h-[390px] flex-col justify-between p-8 md:p-10"><div className="flex flex-col justify-between gap-8 xl:flex-row xl:items-start"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#E2C69D]"><HeartHandshake size={14}/> Wedding command centre</div><h1 className="backstage-display mt-4 max-w-4xl text-5xl md:text-6xl">Plan the emotion. Control every detail.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/65">From the first planning meeting to the last dance—commercials, guests, food, seating, suppliers, payments and live delivery in one wedding record.</p></div><Link href="/calendar" className="flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-backstage-ink"><CalendarDays size={16}/>Start with availability</Link></div>{demoMode && <div className="flex max-w-3xl items-start gap-3 rounded-2xl border border-[#E2C69D]/20 bg-white/[.06] p-4 text-xs leading-5 text-white/65"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-[#E2C69D]"/><span><strong className="text-white">Build mode.</strong> Explore the complete Wedding workspace without configuring authentication. Live portal and payment connections stay off until launch setup.</span></div>}</div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      { label: "Active weddings", value: active.length, note: "In the planning journey", icon: HeartHandshake },
      { label: "Needs attention", value: needsAttention.length, note: "Below 75% readiness", icon: AlertTriangle },
      { label: "Outstanding", value: money.format(outstanding), note: "Remaining balances", icon: PoundSterling },
      { label: "Ready to deliver", value: ready.length, note: "90% readiness or above", icon: ShieldCheck }
    ].map(({ label, value, note, icon: Icon }) => <article key={label} className="backstage-panel rounded-3xl p-5"><div className="flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.12em] text-black/35">{label}</div><div className="backstage-display mt-2 text-3xl">{value}</div><div className="mt-1 text-xs text-black/35">{note}</div></div><div className="grid h-10 w-10 place-items-center rounded-xl bg-backstage-cream text-backstage-gold"><Icon size={17}/></div></div></article>)}</section>

    <section className="grid gap-6 xl:grid-cols-[1fr_.9fr]"><div className="backstage-panel rounded-[28px] p-5 md:p-6"><div className="backstage-kicker">Wedding actions</div><h2 className="backstage-display mt-2 text-3xl">What needs doing next?</h2><div className="mt-5 space-y-3">{active.sort((a, b) => dateValue(a.nextMilestoneDate) - dateValue(b.nextMilestoneDate)).map((wedding) => <Link key={wedding.id} href={`/weddings/${wedding.id}`} className="flex items-center gap-4 rounded-2xl border border-backstage-line bg-white p-4 transition hover:bg-[#FBF9F5]"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${wedding.readinessScore >= 90 ? "bg-[#E7F1E9] text-[#3F6848]" : "bg-amber-50 text-amber-700"}`}>{wedding.readinessScore >= 90 ? <CheckCircle2 size={16}/> : <Clock3 size={16}/>}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{wedding.nextMilestone}</div><div className="mt-1 text-xs text-black/35">{wedding.couple} · {formatDate(wedding.nextMilestoneDate)}</div></div><ArrowRight size={15} className="text-backstage-gold"/></Link>)}</div></div>
      <div className="backstage-panel rounded-[28px] p-5 md:p-6"><div className="backstage-kicker">Wedding journey</div><h2 className="backstage-display mt-2 text-3xl">Built beyond a normal CRM.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Guided meetings", "First, halfway and final planning", Users], ["Guests & seating", "Tables, dietaries and readiness", Users], ["Commercials", "Packages, quotes and balances", PoundSterling], ["Live day", "Running order and team control", Sparkles]].map(([label, note, Icon]) => <div key={String(label)} className="rounded-2xl bg-backstage-cream p-4"><Icon size={17} className="text-backstage-gold"/><div className="mt-3 text-sm font-semibold">{String(label)}</div><div className="mt-1 text-xs leading-5 text-black/40">{String(note)}</div></div>)}</div></div></section>

    <section className="backstage-panel overflow-hidden rounded-[28px]"><div className="flex flex-col gap-4 border-b border-backstage-line p-5 md:flex-row md:items-center md:justify-between"><div><div className="backstage-kicker">Wedding register</div><h2 className="backstage-display mt-1 text-3xl">Every couple</h2></div><div className="flex flex-wrap gap-2"><div className="flex items-center gap-2 rounded-xl border border-backstage-line bg-white px-3"><Search size={14} className="text-black/30"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search couple, package…" className="w-48 bg-transparent py-2.5 text-xs outline-none"/></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-backstage-line bg-white px-3 py-2.5 text-xs outline-none"><option value="active">Active</option><option value="planning">Planning</option><option value="finalising">Finalising</option><option value="ready">Ready</option><option value="live">Live</option><option value="completed">Completed</option></select></div></div><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((wedding) => <Link key={wedding.id} href={`/weddings/${wedding.id}`} className="group overflow-hidden rounded-3xl border border-backstage-line bg-white transition hover:-translate-y-0.5 hover:shadow-soft"><div className="h-28 backstage-wedding-photo"/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="backstage-display text-2xl">{wedding.couple}</h3><div className="mt-1 text-xs text-black/40">{wedding.packageName} · {wedding.coordinator}</div></div><span className="rounded-full bg-[#F2E9DC] px-3 py-1 text-[10px] font-semibold text-[#745A39]">{wedding.readinessScore}%</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="flex items-center gap-2"><CalendarDays size={14} className="text-backstage-gold"/>{formatDate(wedding.eventDate).replace(/,? 2026|,? 2027/, "")}</div><div className="flex items-center gap-2"><Users size={14} className="text-backstage-gold"/>{wedding.dayGuests}/{wedding.eveningGuests}</div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-black/5"><div className="h-full rounded-full bg-backstage-gold" style={{ width: `${wedding.readinessScore}%` }}/></div><div className="mt-4 flex items-center justify-between border-t border-backstage-line pt-4"><div><div className="text-[9px] uppercase tracking-[.1em] text-black/30">Next milestone</div><div className="mt-1 text-xs font-semibold">{wedding.nextMilestone}</div></div><ArrowRight size={15} className="text-backstage-gold"/></div></div></Link>)}</div></section>
  </div>;
}
